// import fetch from "node-fetch";

let blogs1 = [
  {
    _id: "63e790d2735a68cd314d1e35",
    author: "Jayavibhav",
    title: "Sun",
    category: "Social",
    blog_content:
      "The sun is the star at the center of our solar system, and it is by far the most important source of energy for life on Earth. It is a massive, spherical ball of hot plasma, and it is about 109 times larger than the Earth by diameter. The sun is approximately 4.6 billion years old and is expected to remain stable for another 5 billion years.\n\nThe sun's temperature is around 15 million degrees Celsius, and its surface is composed of hydrogen and helium. It generates energy through nuclear fusion, in which hydrogen atoms combine to form helium, releasing vast amounts of energy in the process. The energy generated by the sun is in the form of heat and light, which reaches the Earth as sunlight. The sunlight is essential for photosynthesis, which is the process by which plants convert sunlight into energy, and is the basis of all life on Earth.\n\nThe sun is a dynamic object, with a complex magnetic field and an active atmosphere. It is surrounded by a layer of hot gas called the corona, which can be seen during a total solar eclipse. The sun also has dark spots on its surface called sunspots, which are regions of intense magnetic activity. These sunspots can affect the Earth's climate and have been known to disrupt communications and power grids.\n\nThe sun has been worshipped by many cultures throughout history, and it remains an important symbol in many religions and belief systems. In modern times, scientists continue to study the sun to better understand its behavior and its effects on the Earth's climate and environment.",
    ipfs: "link",
    blog_id: 1,
    image0:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiu9BVPLXAuwSTOmu2J91FjOJOvNP3dc-_iQ&usqp=CAU",
    image1:
      "https://images.unsplash.com/photo-1549849171-09f62448709e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
    image2:
      "https://images.unsplash.com/photo-1575881875475-31023242e3f9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8M3x8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
    image3:
      "https://images.unsplash.com/photo-1593872222524-361daae4f782?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8OHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
    image4:
      "https://images.unsplash.com/photo-1504386106331-3e4e71712b38?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTR8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    keywords: [
      "Sun",
      "Solar system",
      "Nuclear fusion",
      "Photosynthesis",
      "Sunspots",
      "Coronal mass ejection",
    ],
  },
  {
    _id: "63e79de6967ec0f73d14cada",
    title: "Pizza",
    image0:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cGl6emF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    image1:
      "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F19%2F2014%2F07%2F10%2Fpepperoni-pizza-ck-x.jpg&q=60",
    image2:
      "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHBpenphfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    image3:
      "https://images.unsplash.com/photo-1611915365928-565c527a0590?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzJ8fHBpenphfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    image4:
      "https://images.unsplash.com/photo-1542834369-f10ebf06d3e0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDF8fHBpenphfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    blog_id: "2",
    ipfs: "link",
    author: "Nikhil",
    category: "Technology",
    keywords: [
      "Pizza",
      "Italian Cuisine",
      "Toppings",
      "History",
      "Dough",
      "Popular food",
    ],
    blog_content:
      "Pizza is a popular dish that originated in Italy and has since spread around the world. It typically consists of a flatbread base, topped with tomato sauce, cheese, and a variety of other ingredients, such as meats, vegetables, and herbs.\n\nThe exact origins of pizza are unclear, but it is believed to have been developed in Naples, Italy, in the 18th century. The dish was originally a simple snack for working-class people but became more popular as it was introduced to other parts of Italy and beyond.\n\nToday, pizza is one of the most popular foods in the world and is available in a wide range of styles and flavors. Some of the most popular types of pizza include Margherita, pepperoni, and Hawaiian. Pizza can be cooked in a wood-fired oven or a conventional oven, and can also be prepared in a variety of other ways, such as grilled or pan-fried.\n\nPizza is a versatile dish that can be enjoyed on its own or with a variety of side dishes, such as salads or garlic bread. It is also a popular party food and is often served at events and gatherings.\n\nIn conclusion, pizza is a popular and delicious dish that has a rich history and has become a staple of many different cultures. Its versatility and variety have made it a favorite of many people around the world.",
  },
  {
    _id: "63e7ae0a437ff689ff1ade24",
    title: "Lamborghini",
    blog_content:
      "Lamborghini is an Italian luxury sports car manufacturer that was founded in 1963 by Ferruccio Lamborghini. The company is known for producing some of the most stylish, high-performance vehicles in the world, and its cars are prized for their distinctive designs, powerful engines, and impressive speed.\n\nThe first Lamborghini car was the 350 GT, which was released in 1964. This car was followed by a series of iconic models, including the Miura, Countach, Diablo, and Murcielago. Today, the company offers a range of sports cars, including the Aventador, Huracan, and Urus.\n\nOne of the defining characteristics of Lamborghini cars is their powerful engines. Many of the company's vehicles are equipped with V12 engines, which are capable of producing incredibly high amounts of power and torque. This gives the cars an incredible level of acceleration and speed, making them some of the fastest and most thrilling vehicles on the road.\n\nAnother defining feature of Lamborghini cars is their unique and eye-catching designs. The company's vehicles are known for their bold, aggressive styling, and they often feature sharp lines, angular shapes, and angular body panels. This design aesthetic is part of what makes Lamborghini cars so recognizable and iconic.\n\nIn recent years, Lamborghini has also been at the forefront of electric vehicle technology. In 2019, the company introduced the Lamborghini Terzo Millennio, an all-electric concept car that showcased the company's vision for the future of sports cars.\n\nOverall, Lamborghini is a company that is synonymous with luxury, performance, and style. Whether you are a car enthusiast, a collector, or simply someone who appreciates beautiful vehicles, there is no denying the appeal of a Lamborghini. These cars are some of the most sought-after and admired vehicles in the world, and they continue to push the boundaries of what is possible in the world of high-performance sports cars",
    image0:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/0cae088f-f2cd-4405-995d-139802c40532",
    image1:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/0454ba78-628c-4abb-8782-cad9b69596bb",
    image2:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/071e5fa8-cbec-47e3-9fdc-2b74c40cc475",
    image3:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/005d1c3f-ed78-4027-bfa9-69cd3cefb0dd",
    image4:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/0642e719-11e5-45f5-9d75-54dbacd0c7d3",
    keywords: [
      "Ferruccio Lamborghini",
      "Lamborghini",
      "Lamborghini cars",
      "Italian luxury sports",
      "Cars",
      "Avendator",
    ],
    ipfs: "https://ipfs.moralis.io:2053/ipfs/QmQpg3HY2daKSUWPTMCKBPMYvjfLFVVNjd61gLswSJoEyM/reportLamborghini car",
    nft: "https://ipfs.moralis.io:2053/ipfs/QmTwt6WUNr2HCDgG9uxfVzCddGDvns9XpTdbph3ppHhpYf/nftofLamborghini car",
    category: "Cars",
    author: "Balayya",
  },
  {
    _id: "63e7b22f437ff689ff1b6ac8",
    title: "Ferrari",
    blog_content:
      "Ferrari is an Italian luxury sports car manufacturer based in Maranello, Italy. Founded by Enzo Ferrari in 1947, Ferrari has become one of the world's most well-known and recognizable car brands. The company is known for producing high-performance cars that offer speed, power, and sophistication.\n\nFerrari's signature product is the Ferrari sports car, which is known for its sleek design, powerful engine, and exceptional handling. Over the years, the company has introduced several iconic models, including the Ferrari 250 GTO, the Ferrari 288 GTO, the Ferrari F40, the Ferrari Enzo, and the Ferrari LaFerrari. Each of these models has become a classic in its own right and has helped cement Ferrari's reputation as a leading producer of premium sports cars.\n\nIn addition to its sports cars, Ferrari has also produced several racing cars over the years. The company has a long and successful history in motorsport, and it has won numerous races and championships in a variety of motorsport categories, including Formula One, endurance racing, and sports car racing.\n\nFerrari is also known for its innovative use of technology. The company has been at the forefront of automotive engineering, and it has consistently pushed the boundaries of what is possible with modern sports cars. For example, Ferrari was one of the first car manufacturers to incorporate electronic driver aids, such as traction control and stability control, into its cars.\n\nDespite its rich heritage and reputation for producing some of the world's finest sports cars, Ferrari is not content to rest on its laurels. The company continues to innovate and push the boundaries of what is possible, and it is constantly working to improve its products and create new and exciting vehicles for its customers.\n\nIn conclusion, Ferrari is a true icon of the automotive world. With its rich heritage, high-performance cars, and commitment to innovation, Ferrari is a brand that is synonymous with excellence and sophistication. Whether you're a fan of sports cars or just admire Ferrari's engineering and design, there is no denying that this company is one of the most important and influential in the automotive industry.",
    image0:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/005d1c3f-ed78-4027-bfa9-69cd3cefb0dd",
    image1:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/0b18edf0-ef5e-43a0-b587-08f65f1fccb6",
    image2:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/05059c4b-2a8f-499a-8228-ec4a698400b5",
    image3:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/015a1452-da92-43f3-b347-1a4e55e5b3aa",
    image4:
      "https://lexica-serve-encoded-images.sharif.workers.dev/md/017bbda8-779a-4924-9a5c-72c41eb708ca",
    keywords: [
      "Italian luxury sports",
      "Ferrari",
      "Based in Maranello",
      "Italian luxury",
      "Sports cars",
      "LaFerrari",
    ],
    ipfs: "https://ipfs.moralis.io:2053/ipfs/QmeAmsxqFTMUk6LsDj8EQFje7wyeb4bzDrXVrxuwyjzPzi/reportFerrari",
    nft: "https://ipfs.moralis.io:2053/ipfs/QmXB7umya4G9tNx5zHzYQtk4V4b2B6tFZuwQ7pn2x3hEnU/nftofFerrari",
    category: "Cars",
    author: "Nikhil",
  },
];

// async function api() {
//   await fetch(url, {
//     method: "GET",
//     body: JSON.stringify(payload),
//   })
//     .then((response) => response.json())
//     .then((data) => console.log(data))
//     .catch((error) => console.error(error));
// }

// api();

// blogs = await fetch("http://127.0.0.1:5000/array")
//   .then((response) => response.json())
//   // .then((data) => console.log(data))
//   .catch((error) => console.error(error));
// console.log(blogs);
// import { blogs } from "./server.js";

const blogs = await fetch("http://127.0.0.1:5000/array")
  .then((response) => response.json())
  // .then((data) => console.log(data))
  .catch((error) => console.error(error));
console.log(blogs);

// export const blogs = blogs1;
export const blogArray = blogs;
